### ISSUE TITLE
plural expressions can brake syntax highlighting

### ISSUE THREAD

**Issue by jigfox** [dlvandenberg/tree-sitter-angular#16]
```ts
@Component(/* */)
export class SomeComponent {
  public list: string[];
}
```

```html
<div>
  {list.length, plural, =1 {One Item} other {{{list.length}} Items}}
</div>
<span>some mor text</span>
```

will look like this:

<img width="492" alt="image" src="https://github.com/dlvandenberg/tree-sitter-angular/assets/110414/714d63b1-625c-4832-afc7-621766c699e3">

everything after the expression looses highlighting

**Comment by dlvandenberg** [comment]
Ah, this is the [ICU](https://angular.io/guide/i18n-common-prepare#icu-expressions) expression format. It is currently not supported. 

I will look into this when I have time.

**Comment by jigfox** [comment]
@dlvandenberg I have opened PR #18 to solve this, comments and suggestions will be much appreciated
