### ISSUE TITLE
Does indentation work?

### ISSUE THREAD

**Issue by maxrzaw** [dlvandenberg/tree-sitter-angular#24]
Does this grammar include support for indentation?

Unless I have it set up incorrectly the indentation does not work with the new control flow syntax. I don't think I have it set up incorrectly, because the highlighting is working correctly.

This is what the indentation should be:
```html
<div>
  @if (true) {
    <p>tree sitter indentation does not work for this line</p>
  }
</div>
```
But this is what tree sitter indentation results in:
```html
<div>
  @if (true) {
  <p>tree sitter indentation does not work for this line</p>
  }
</div>
```

**Comment by dlvandenberg** [comment]
Currently it does not. Personally I use prettier for the indentations. I could look into indentation support.

**Comment by Zaxiure** [comment]
I'm also having this issue, gets kinda annoying to deal with when not using a formatter especially if there's a lot of nested if/for statements. When inserting a new line inside a if/for statement it also doesn't put the cursor on the right place resulting in constant corrections.

**Comment by dlvandenberg** [comment]
I've added indentation support to https://github.com/nvim-treesitter/nvim-treesitter/pull/6848

**Comment by dlvandenberg** [comment]
Merged in https://github.com/nvim-treesitter/nvim-treesitter/pull/6928

**Comment by maxrzaw** [comment]
Just updated and it is working great. Thanks so much!!!
