### ISSUE TITLE
Support for Analog SFCs

### ISSUE THREAD

**Issue by k3dom** [dlvandenberg/tree-sitter-angular#26]
The meta framework for angular [analog.js](https://analogjs.org/) now supports a new experimental file format called [Analog SFCs](https://analogjs.org/docs/experimental/sfc). I am not sure if supporting this format is within the scope of this project but if yes, it would be awesome seeing support for it added.

**Comment by dlvandenberg** [comment]
No this is something that a `tree-sitter-analog` parser should handle . ;)
