### ISSUE TITLE
Hover not working: "method textDocument/hover is not supported..."

### ISSUE THREAD

**Issue by miloschwartz** [dlvandenberg/tree-sitter-angular#29]
`method textDocument/hover is not supported by any of the servers registered for the current buffer`

I seem to be unable to use hover on Angular elements with this plugin installed. However they work if the plugin is disabled/uninstalled.

`
    use {
        'nvim-treesitter/nvim-treesitter', run = ':TSUpdate',
        commit = 'ef267f0c285928ea3a0d3362a260a0728fd4a146'
    }
`

`
	use {
		"dlvandenberg/tree-sitter-angular",
		commit = "10f21f3f1b10584e62ecc113ab3cda1196d0ceb8"
	}
`

**Comment by dlvandenberg** [comment]
Do you have a plugin in `.config/nvim/angular.lua` with the following:
```lua
vim.filetype.add({
  pattern = {
    [".*%.component%.html"] = "angular.html",
  },
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = "angular.html",
  callback = function()
    vim.treesitter.language.register("angular", "angular.html")
  end,
})
```

What version of nvim are you using?

**Comment by dlvandenberg** [comment]
In the nightly neovim build, filetype detection is added for Angular Templates.
Filetype is htmlangular. Please adjust your LSP config accordingly.

You need to update to the latest nvim-treesitter version also, as the angular parser is coupled to the new filetype.
