### ISSUE TITLE
Alternative filetype solution?

### ISSUE THREAD

**Issue by wmaurer** [dlvandenberg/tree-sitter-angular#31]
Any ideas for an alternative filetype solution?

The recommended solution here is to match on files ending with .component.html

However not all projects use this convention. For example the Angular Material project doesn't: https://github.com/angular/components/blob/main/src/material/button/button.html

I don't know how it does it, but the VScode plugin manages to detect if it's an Angular HTML file. ...

**Comment by dlvandenberg** [comment]
I am working on adding filetype detection into vim itself, by checking the file contents

**Comment by dlvandenberg** [comment]
New filetype detection in [afbe7736a4966f22146d857f246eac01cd080773 ](https://github.com/neovim/neovim/commit/afbe7736a4966f22146d857f246eac01cd080773)

Update to neovim nightly and nvim-treesitter latest
