### ISSUE TITLE
The new Angular control flow syntax is now supported by nvim-treesitter

### ISSUE THREAD

**Issue by Zooce** [dlvandenberg/tree-sitter-angular#35]
Just a note since I updated plugins this morning and noticed: https://github.com/nvim-treesitter/nvim-treesitter/commit/03883041b21413444df1cb22d9483d3fffb889c4

Turns out nvim-treesitter now supports the new Angular control flow syntax.

**Comment by dlvandenberg** [comment]
That is correct.
