### ISSUE TITLE
Filetype detection.

### ISSUE THREAD

**Issue by ask-786** [dlvandenberg/tree-sitter-angular#37]
I have created a new issue in neovim about detecting `htmlangular` filetype.

https://github.com/neovim/neovim/issues/29808

can we do something about it here?

**Comment by dlvandenberg** [comment]
You could create a plugin yourself that marks the filetype as `htmlangular` when it matches the pattern `*.component.html`.
E.g.:
```
vim.filetype.add({
  pattern = {
    [".*%.component%.html"] = "htmlangular",
  },
})
```
