### ISSUE TITLE
Neovim panics with "nvim: src/scanner.c:370: scan: Assertion `(uint32_t)((&scanner->tags)->size - 1) < (&scanner->tags)->size' failed. " in the new control flow syntax

### ISSUE THREAD

**Issue by ninoDeme** [dlvandenberg/tree-sitter-angular#39]
when opening or editing some angular template files with the new angular control flow neovim willl always crash with the following error: 
`nvim: src/scanner.c:370: scan: Assertion '(uint32_t)((&scanner->tags)->size - 1) < (&scanner->tags)->size' failed.`

[![asciinema CLI
demo](https://asciinema.org/a/LMIgthoNMyFoqrZtQTeUs7n6B.svg)](https://asciinema.org/a/LMIgthoNMyFoqrZtQTeUs7n6B?autoplay=1)

contents of the file used in the example: 
``` html
@if (error(); as erroObj) {
    <ec-error [erro]="erroObj" />
}

@if (divisao.enableCalendar) {
<section>
    <div class="w-full px-4 flex flex-row items-center gap-4">
    </div>
    @if (diaSelecionado(); as dia) {
        <section class="flex px-4 w-full items-center mt-3">
            <span ec-body si>{{ dia.date | date: 'fullDate' }}</span>
        </section>
    }       
</section>
}
```

**Comment by ask-786** [comment]
got the same error

**Comment by zanesterling** [comment]
Same here. Started happening for me today. I first saw it on a different file, but can reproduce with ninoDeme@'s sample.

Opening that file with `nvim sample.ng.html` clears the terminal, then exits the program with error code 134.

Typing the sample into a new blank file, it fails reliably upon typing the second `}`: line 11, character 60.

**Comment by zanesterling** [comment]
The error message is an array bounds check in `array_get`, called from `array_back`. The direct cause of the bounds check seems to be that `scanner->tags` is empty.

**Comment by zanesterling** [comment]
Here's a trimmed down version of @ninoDeme's repro sample that still triggers it for me every time:

```
@if (error(); as erroObj) {
}

@if (divisao.enableCalendar) {
<div class="w-full px-4 flex flex-row items-center">
</div>
<section class="flex px-4 w-full items-center mt-3">
  <span ec-body si>{{ dia.date | date: 'fullDate' }}
```

Everything left in this sample seems to be load-bearing to trigger the bug.

**Comment by zanesterling** [comment]
Ah, actually I can trim it even a bit more:

```
@if (error(); as erroObj) {
}

@if (divisao.enableCalendar) {
<div class="w-full px-4 flex flex-row items-center">
</div>
<section class="flex px-4 w-full items-center mt-3">
  <span ec-body si>{{}}
```

**Comment by ninoDeme** [comment]
There appears to be two problems that lead to this error:
Incorrect parsing of the control flow syntax due to wrong precedence rules in the grammar file (you can notice this when sometimes the highlighting gets broken when multiple @if statements are following one another)
The custom scanner c code then tries to close and create a interpolation block "{{}}" that should be in the tags array, but doesnt exist due to the invalid syntax tree

here is the actual minimal example that causes this error:

``` html
@if (x) {
}

@if (x) {
  {{}}
}

```

if you just remove the interpolation block the generated ast becomes this: 

``` tree-sitter
(document [0, 0] - [5, 0]
  (if_statement [0, 0] - [4, 1]
    (control_keyword [0, 1] - [0, 3])
    condition: (if_condition [0, 5] - [0, 6]
      (expression [0, 5] - [0, 6]
        (identifier [0, 5] - [0, 6])))
    (ERROR [0, 6] - [3, 6]
      (statement_block [0, 8] - [1, 1])
      (control_keyword [3, 1] - [3, 3])
      (ERROR [3, 5] - [3, 6]))
    consequence: (statement_block [3, 8] - [4, 1])))
```
the second if block becomes conjoined with the first one.
