### ISSUE TITLE
Does not handle some edge cases related to ngStyle

### ISSUE THREAD

**Issue by Ryntak94** [dlvandenberg/tree-sitter-angular#41]
I've been unable to reproduce this problem outside of my companies proprietary code, so forgive me for not being able to provide much more context.

Here is a screenshot of the current issue:

![image](https://github.com/user-attachments/assets/676e4c31-042f-41d8-a622-8120c3051329)

This seems consistent when replacing the `%` with multiple other special characters.
`!*(-+{<>/?`
but not with: `~@#$^&)}[]\|,.;:`
If I move the `* 100` inside of the parentheses, no issue.
![image](https://github.com/user-attachments/assets/2d248078-bc4a-475a-80fa-dd5c940c5707)

Additionally, 
![image](https://github.com/user-attachments/assets/82d87356-3f66-48b6-aa1b-6fb3c89204ae)
You can see here if I remove the () around `currentlyAt / end` there is a separate issue with the highlighting of the `* 100`

However, you can see here that there is no issue
![image](https://github.com/user-attachments/assets/f6ab77df-7b83-4803-9eaa-f3fbc19b8e72)

If I make the following modification, it seems to completely break the highlighting:

![image](https://github.com/user-attachments/assets/faf4e89e-c73f-46cf-8bb5-488f05de9d73)

Let me know if I can provide more information. Unfortunately, I do not think I will be able to replicate it in a standalone repo. Happy to help troubleshoot/test changes.

**Comment by dlvandenberg** [comment]
Hi @Ryntak94 , thanks for the detailed report. I will look into this when I have time.
