### ISSUE TITLE
`%` not working as expected

### ISSUE THREAD

**Issue by shljsl75891** [dlvandenberg/tree-sitter-angular#48]
Pressing % in `htmlangular` filetype not jumping between opening and closing tags. Is it a known issue or required some config to work as expected ?
```
-- For Angular treesitter
vim.filetype.add({
	pattern = {
		[".*%.component%.html"] = "htmlangular", -- Sets the filetype to `htmlangular` if it matches the pattern
	},
})
```

I've added this in my config as per README. Neovim Version: `NVIM v0.10.1`

**Comment by dlvandenberg** [comment]
I think this is because your vim version does not load the html ftplugin when a `htmlangular` filetype is detected.

Could you create a ftplugin (e.g. in `~/.config/nvim/ftplugin/htmlangular.vim` yourself using this:
```vim
runtime! ftplugin/html.vim
```

**Comment by shljsl75891** [comment]
Thank you @dlvandenberg. I created a file in `~/.config/nvim/after/htmlangular.lua` and added the same command . Now, it's working and issue is resolved.
```lua
vim.cmd("runtime! ftplugin/html.vim")
```
